//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SashaPassGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SashaPassGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spicy
        ///Tangy
        ///Tiny
        ///Huge
        ///Wide
        ///Thin
        ///Cute
        ///Smiley
        ///pretty
        ///Bald
        ///Hairy
        ///Tasty
        ///Sour
        ///Fruity
        ///Minty
        ///Slimey
        ///good
        ///Pointed
        ///Fresh
        ///Intelligent
        ///Handsome
        ///Happy
        ///Cool
        ///Funny
        ///Colourful
        ///Silly
        ///glowing
        ///.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frog
        ///Cat
        ///Dog
        ///Lizard
        ///Bird
        ///Swan
        ///Duck
        ///Pangolin
        ///Elephant
        ///Gorilla
        ///Dolphin
        ///Shark
        ///hen
        ///Whale
        ///crow
        ///Aardvark
        ///Falcon
        ///Finch
        ///Mouse
        ///Horse
        ///Lion
        ///Sparrow
        ///Boar
        ///tiger
        ///apple
        ///orange
        ///Panda
        ///Dingo
        ///Ant
        ///Baboon
        ///Badger
        ///magpie
        ///Bandicoot
        ///Bat
        ///Eagle
        ///Bison
        ///rhino
        ///spider
        ///Monkey
        ///vulture
        ///jackal
        ///crane
        ///mallard
        ///kangaroo
        ///Ferret
        ///Wombat
        ///Koala
        ///Catfish
        ///Parrot
        ///hyena
        ///crab
        ///lemur
        ///ButterFly
        ///goose
        ///Cow
        ///Zebra
        ///Goat
        ///Koala
        ///Otter
        ///Possums
        ///Python
        ///Lizard
        ///turtle
        ///Sponge
        ///Starfish
        ///squirrel
        ///plankton.
        /// </summary>
        internal static string animals {
            get {
                return ResourceManager.GetString("animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red
        ///orange
        ///yellow
        ///green
        ///blue
        ///indigo
        ///violet
        ///Brown
        ///Purple
        ///Cyan
        ///Pink
        ///Black
        ///White
        ///Scarlet
        ///.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap communities_logo {
            get {
                object obj = ResourceManager.GetObject("communities-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Hat {
            get {
                object obj = ResourceManager.GetObject("Hat", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dancing
        ///Jumping
        ///Hopping
        ///Lying
        ///Singing
        ///Running
        ///Sleeping
        ///Laughing
        ///Writing
        ///Walking.
        /// </summary>
        internal static string verbs {
            get {
                return ResourceManager.GetString("verbs", resourceCulture);
            }
        }
    }
}
