//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SashaPassGen.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SashaPassGen.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitter
        ///Bland
        ///Spicy
        ///Tangy
        ///Tiny
        ///Massive
        ///Huge
        ///Wide
        ///Thin
        ///Thick
        ///Cute
        ///Smiley
        ///pretty
        ///Bald
        ///Hairy
        ///Tasty
        ///Salty
        ///Sour
        ///Fruity
        ///Minty
        ///Slimey
        ///good
        ///Pointed
        ///Fresh
        ///Intelligent
        ///Handsome
        ///Happy
        ///Elongated
        ///Cool
        ///Funny
        ///bad
        ///Colourful
        ///Silly
        ///Jealous.
        /// </summary>
        internal static string adjectives {
            get {
                return ResourceManager.GetString("adjectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to frog
        ///Cat
        ///Dog
        ///Lizard
        ///Bird
        ///Swan
        ///Duck
        ///Pangolin
        ///Elephant
        ///Gorilla
        ///Dolphin
        ///Shark
        ///Whale
        ///Aardvark
        ///Lion
        ///tiger
        ///PandaBear
        ///Dingo
        ///Ant
        ///Baboon
        ///Badger
        ///magpie
        ///Bandicoot
        ///Bat
        ///Beaver
        ///BaldEagle
        ///Eagle
        ///Bison
        ///rhino
        ///spiderMonkey
        ///vulture
        ///jackal
        ///crane
        ///mallard
        ///password
        ///kangaroo
        ///Ferret
        ///Wombat
        ///Koala 
        ///Catfish
        ///Peacock
        ///hyena
        ///lemur
        ///ButterFly
        ///goose
        ///human.
        /// </summary>
        internal static string animals {
            get {
                return ResourceManager.GetString("animals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red
        ///orange
        ///yellow
        ///green
        ///blue
        ///indigo
        ///violet
        ///.
        /// </summary>
        internal static string colors {
            get {
                return ResourceManager.GetString("colors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap communities_logo {
            get {
                object obj = ResourceManager.GetObject("communities-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ball
        ///bat
        ///bed
        ///book
        ///boy
        ///bun
        ///can
        ///cake
        ///cap
        ///car
        ///cat
        ///cow
        ///cub
        ///cup
        ///dad
        ///day
        ///dog
        ///doll
        ///dust
        ///fan
        ///feet
        ///girl
        ///gun
        ///hall
        ///hat
        ///hen
        ///jar
        ///kite
        ///man
        ///map
        ///men
        ///mom
        ///pan
        ///pet
        ///pie
        ///pig
        ///pot
        ///rat
        ///son
        ///sun
        ///toe
        ///tub
        ///van
        ///apple
        ///arm
        ///banana
        ///bike
        ///bird
        ///book
        ///chin
        ///clam
        ///class
        ///clover
        ///club
        ///corn
        ///crayon
        ///crow
        ///crown
        ///crowd
        ///crib
        ///desk
        ///dime
        ///dirt
        ///dress
        ///fang
        ///field
        ///flag
        ///flower
        ///fog
        ///game
        ///heat
        ///hill
        ///home
        ///horn
        ///hose
        ///joke
        ///juice
        ///kite
        ///lake
        ///maid
        ///mask
        ///mice
        ///milk
        ///mint
        ///meal
        ///meat
        ///moon
        ///mother
        ///mor [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nouns {
            get {
                return ResourceManager.GetString("nouns", resourceCulture);
            }
        }
    }
}
